# Generated by Django 4.0 on 2021-12-11 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(auto_created=True, default=False)),
                ('progress', models.FloatField(auto_created=True, default=0.0)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.FloatField(default=0.1)),
                ('due_date', models.DateTimeField()),
                ('in_project', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(auto_created=True, default=False)),
                ('progress', models.FloatField(auto_created=True, default=0)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.FloatField(default=0.1)),
                ('due_date', models.DateTimeField()),
                ('items', models.ManyToManyField(to='todos.Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.user'),
        ),
        migrations.AddField(
            model_name='item',
            name='subitems',
            field=models.ManyToManyField(to='todos.Item'),
        ),
    ]
