# Generated by Django 4.0 on 2021-12-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='subitems',
            field=models.ManyToManyField(blank=True, to='todos.Item'),
        ),
    ]
