# Generated by Django 4.0 on 2021-12-12 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todos', '0002_alter_item_subitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('name', 'description', 'due_date', 'priority', 'progress', 'completed')},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('name', 'description', 'due_date', 'priority', 'progress', 'completed')},
        ),
        migrations.RemoveField(
            model_name='item',
            name='in_project',
        ),
        migrations.RemoveField(
            model_name='item',
            name='subitems',
        ),
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='item',
            name='author',
        ),
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.ManyToManyField(through='todos.ItemUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='itemuser',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.item'),
        ),
        migrations.AddField(
            model_name='itemuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
